// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFOhF1oI6HOGcwW4baK76t-nnuN4MYRHw',
    appId: '1:754488993341:web:9b818d0f58d1e0128fec54',
    messagingSenderId: '754488993341',
    projectId: 'sistema-rick',
    authDomain: 'sistema-rick.firebaseapp.com',
    storageBucket: 'sistema-rick.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl0Zxa_kTJMSQn9FFFjgT_lXIjSNdrXBg',
    appId: '1:754488993341:android:f7cc3b35e26411e98fec54',
    messagingSenderId: '754488993341',
    projectId: 'sistema-rick',
    storageBucket: 'sistema-rick.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGj0WTjQM9KkpEhbZnrq2ikZWoyYOfvto',
    appId: '1:754488993341:ios:52e6a43abfa1ec648fec54',
    messagingSenderId: '754488993341',
    projectId: 'sistema-rick',
    storageBucket: 'sistema-rick.appspot.com',
    iosClientId: '754488993341-5crf99ileijc1egeu0cvqa4m76922v8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistema',
  );
}
